from ...db_connect import Base
from sqlalchemy import Column, String, Date, Integer, Float, DateTime, Boolean, func


class VoterDetailModel(Base):
    __tablename__ = 'ev_roster'
    vuid = Column(Integer, primary_key=True)
    county = Column(String)
    fullName = Column(String)
    firstName = Column(String)
    lastName = Column(String)
    dob = Column(Date, nullable=True)
    age = Column(Integer, nullable=True)
    age_range = Column(String, nullable=True)
    sd = Column(String)
    hd = Column(String)
    cd = Column(String)
    precinct = Column(String, nullable=True)
    poll_place_id = Column(String, nullable=True)
    poll_place_name = Column(String, nullable=True)
    vote_method = Column(String)
    vote_date = Column(Date)
    day_in_ev = Column(Integer)
    vep_registration = Column(Boolean, nullable=True)
    gen18 = Column(String, nullable=True)
    gen19 = Column(String, nullable=True)
    gen20 = Column(String, nullable=True)
    gen21 = Column(String, nullable=True)
    gen22 = Column(String, nullable=True)
    gen23 = Column(String, nullable=True)
    pri18 = Column(String, nullable=True)
    pri20 = Column(String, nullable=True)
    pri22 = Column(String, nullable=True)
    pri24 = Column(String, nullable=True)
    primary_count = Column(Integer)
    general_count = Column(Integer)
    primary_count_dem = Column(Integer)
    primary_count_rep = Column(Integer)
    primary_percent_dem = Column(Float)
    primary_percent_rep = Column(Float)
    general_percent_dem = Column(Float)
    general_percent_rep = Column(Float)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())
